// <auto-generated />
using System;
using Fiap.Web.Students.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.Web.Students.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260605180145_AddRepresentativeAndClient")]
    partial class AddRepresentativeAndClient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Web.Students.Models.ClientModel", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CLIENT_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("BIRTH_DATE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("Observation")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("OBSERVATION");

                    b.Property<int>("RepresentativeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("REPRESENTATIVE_ID");

                    b.HasKey("ClientId");

                    b.HasIndex("RepresentativeId");

                    b.ToTable("TB_CLIENT", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Students.Models.RepresentativeModel", b =>
                {
                    b.Property<int>("RepresentativeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("REPRESENTATIVE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepresentativeId"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("CPF");

                    b.Property<string>("RepresentativeName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("REPRESENTATIVE_NAME");

                    b.HasKey("RepresentativeId");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("TB_REPRESENTATIVE", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Students.Models.ClientModel", b =>
                {
                    b.HasOne("Fiap.Web.Students.Models.RepresentativeModel", "Representative")
                        .WithMany()
                        .HasForeignKey("RepresentativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Representative");
                });
#pragma warning restore 612, 618
        }
    }
}
