// <auto-generated />
using System;
using Fiap.Web.Students.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.Web.Students.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260607145741_CreateAllRemainingTables")]
    partial class CreateAllRemainingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Web.Students.Models.ClientModel", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CLIENT_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("BIRTH_DATE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("Observation")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("OBSERVATION");

                    b.Property<int>("RepresentativeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("REPRESENTATIVE_ID");

                    b.HasKey("ClientId");

                    b.HasIndex("RepresentativeId");

                    b.ToTable("TB_CLIENT", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Students.Models.OrderModel", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("DATE");

                    b.Property<int>("StoreId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("OrderId");

                    b.HasIndex("ClientId");

                    b.HasIndex("StoreId");

                    b.ToTable("TB_ORDER", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Students.Models.OrderProductModel", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProductId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProductModel");
                });

            modelBuilder.Entity("Fiap.Web.Students.Models.ProductModel", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("NUMBER(18,2)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ProductId");

                    b.HasIndex("SupplierId");

                    b.ToTable("TB_PRODUCT", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Students.Models.RepresentativeModel", b =>
                {
                    b.Property<int>("RepresentativeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("REPRESENTATIVE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepresentativeId"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("CPF");

                    b.Property<string>("RepresentativeName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("REPRESENTATIVE_NAME");

                    b.HasKey("RepresentativeId");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("TB_REPRESENTATIVE", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Students.Models.StoreModel", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("StoreId");

                    b.ToTable("TB_STORE", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Students.Models.SupplierModel", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("SupplierId");

                    b.ToTable("TB_SUPPLIER", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Students.Models.ClientModel", b =>
                {
                    b.HasOne("Fiap.Web.Students.Models.RepresentativeModel", "Representative")
                        .WithMany()
                        .HasForeignKey("RepresentativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Representative");
                });

            modelBuilder.Entity("Fiap.Web.Students.Models.OrderModel", b =>
                {
                    b.HasOne("Fiap.Web.Students.Models.ClientModel", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fiap.Web.Students.Models.StoreModel", "Store")
                        .WithMany("Orders")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Fiap.Web.Students.Models.OrderProductModel", b =>
                {
                    b.HasOne("Fiap.Web.Students.Models.ProductModel", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fiap.Web.Students.Models.OrderModel", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Fiap.Web.Students.Models.ProductModel", b =>
                {
                    b.HasOne("Fiap.Web.Students.Models.SupplierModel", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Fiap.Web.Students.Models.OrderModel", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("Fiap.Web.Students.Models.ProductModel", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("Fiap.Web.Students.Models.StoreModel", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Fiap.Web.Students.Models.SupplierModel", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
